development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("http://redis-15410.c81.us-east-1-2.ec2.cloud.redislabs.com:15410/") { "redis://localhost:6379/1" } %>
  channel_prefix: piggy_bank_production
