meta_product_name: "Piggy Bank"
meta_title: "Piggy Bank"
meta_description: "Acompanhe as tarefas e recompensas de seus filhos. Prazos escolares cumpridos, mesada sem discussões, metas conquistadas!"
meta_image: "cover.png" # should exist in `app/assets/images/`
